[package]
name = "llms"
version = "0.1.0"
edition = "2021"

[dependencies]
kalosm = {version = "0.3.2", features = ["language", "sound", "vision"]}
tokio = {version = "1.40.0", features = ["full"]}
futures-util = "0.3.30"
